name: Sync with GitLab
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITLAB_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
      
      - name: Push to GitLab
        run: |
          git remote add gitlab git@gitlab.univ-lille.fr:yann.renard.etu/iut-sae1.02.git
          git push -u gitlab main --force
